dataset:
  train:
    target: core.dataset.spc_image_mosaic.SPCDataset_Mosaic
    params:
      file_list: /media/agarg54/Extreme SSD/dataset_files/combined_dataset.txt
      file_backend_cfg:
        target: core.dataset.file_backend.HardDiskBackend
      out_size: 768
      crop_type: "center"
      use_hflip: False
      bits: 3
  val:
    target: core.dataset.spc_image_mosaic.SPCDataset_Mosaic
    params:
      file_list: /media/agarg54/Extreme SSD/dataset_txt_files/full_test_set.txt
      file_backend_cfg:
        target: core.dataset.file_backend.HardDiskBackend
      out_size: 768
      crop_type: "center"
      use_hflip: False
      bits: 3


batch_transform:
  target: core.dataset.batch_transform.IdentityBatchTransform
  # params:

train:
  # experiment directory path
  sd_path: /media/agarg54/Extreme SSD/sd3.5_large.safetensors
  exp_dir: /nobackup1/aryan/weights/sd35_qvae_mosaic
  learning_rate: 1e-5
  batch_size: 1
  num_workers: 24
  train_steps: 3_000_000
  log_every: 500
  ckpt_every: 10_000
  image_every: 500
  val_every: 10_000
  # Loss params
  loss_mode: "mse_ls_gt_perceptual" # "mse_ls", "ls_only", "ls_gt", "ls_gt_perceptual"
  loss_scales:
    lsa: 5.
    mse: 5.
    gt: 0
    perceptual: 2.5
