dataset:
  train:
    target: core.dataset.spc_image_mosaic.SPCDataset_Mosaic
    params:
      file_list: /mnt/disks/behemoth/datasets/dataset_txt_files/combined_dataset.txt
      file_backend_cfg:
        target: core.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: "center"
      use_hflip: False
      bits: 3
  val:
    target: core.dataset.spc_image_mosaic.SPCDataset_Mosaic
    params:
      file_list: /mnt/disks/behemoth/datasets/dataset_txt_files/random_val.txt
      file_backend_cfg:
        target: core.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: "center"
      use_hflip: False
      bits: 3


batch_transform:
  target: core.dataset.batch_transform.IdentityBatchTransform
  # params:

train:
  # experiment directory path
  sd_path: /home/argar/apgi/gqvr_sd35/pretrained_ckpt/sd3.5_large.safetensors
  exp_dir: /home/argar/apgi/gqvr_sd35/experiments/DiT_Stage2/s2_mosaic_3bit_5k
  vae_path: /home/argar/apgi/gqvr_sd35/experiments/VAEs_Stage1/mosaic_3bit/checkpoints/0250000.pt
  ##########################
  # TODO:
  ##########################
  lora_rank: 64
  lora_modules: ["x_embedder.proj", "context_block.attn.qkv", "context_block.attn.proj", "x_block.attn.qkv", "x_block.attn.proj", "ff.net.0.proj", "ff.net.2", "final_layer.linear"]
  ###########################

  learning_rate: 1e-5
  batch_size: 1
  
  num_workers: 96
  
  train_steps: 5002
  
  log_every: 1000
  ckpt_every: 5000
  image_every: 5000
  val_every: 5000
  
  # Loss params
  loss_scales:
    lambda_gan: 0.5
    lambda_lpips: 5
    lambda_l2: 1
